//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Niva.Erp.Models.Conta
{
    using Abp.Domain.Entities;
    using Abp.Domain.Entities.Auditing;
    using Niva.Erp.Models.Conta.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public class ForeignOperation : AuditedEntity<int>,  IMustHaveTenant
    {
        [ForeignKey("BankAccount")]
        public int BankAccountId { get; set; }
        public virtual BankAccount BankAccount { get; set; }

        public virtual DateTime DocumentDate { get; set; }

        public virtual string DocumentNumber { get; set; }

        public virtual DateTime OperationDate { get; set; }
        
        public virtual IList<ForeignOperationsDetails> ForeignOperationsDetails { get; set; }

        [ForeignKey("DocumentType")]
        public int DocumentTypeId { get; set; }
        public virtual DocumentType DocumentType { get; set; }

        [ForeignKey("Currency")]
        public int CurrencyId { get; set; }
        public virtual Currency Currency { get; set; }

      

        public virtual State State { get; set; }

       
        public int TenantId { get; set; }
    }
}

