//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Niva.Erp.Models.Conta
{
    using Abp.Domain.Entities;
    using Abp.Domain.Entities.Auditing;
    using Niva.Erp.Models.Economic;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public class ForeignOperationsDetails : AuditedEntity<int>, IMustHaveTenant
    {
        [ForeignKey("DocumentType")]
        public int DocumentTypeId { get; set; }
        public virtual DocumentType DocumentType { get; set; }

        public virtual DateTime DocumentDate { get; set; }

        public virtual string DocumentNumber { get; set; }

        public virtual string OriginalDetails { get; set; }

        public virtual decimal Value { get; set; }

        public virtual decimal ValueCurr { get; set; }

        [ForeignKey("ForeignOperation")]
        public int ForeignOperationId { get; set; }
        public virtual ForeignOperation ForeignOperation { get; set; }


        [ForeignKey("PaymentOrder")]
        public int? PaymentOrderId { get; set; }
        public virtual PaymentOrders PaymentOrder { get; set; }

        public virtual IList<ForeignOperationsAccounting> OperationsAccounting { get; set; }

        public int TenantId { get; set; }
    }

    public class ForeignOperationsAccounting : AuditedEntity<int>, IMustHaveTenant
    {
        public virtual string Details { get; set; }

        public virtual decimal Value { get; set; }

        public virtual decimal ValueCurr { get; set; }

        [ForeignKey("Debit")]
        public int? DebitId { get; set; }
        public virtual Account Debit { get; set; }

        [ForeignKey("Credit")]
        public int? CreditId { get; set; }
        public virtual Account Credit { get; set; }

        [ForeignKey("FgnOperationsDetail")]
        public int FgnOperationsDetailId { get; set; }
        public virtual ForeignOperationsDetails FgnOperationsDetail { get; set; }

        [ForeignKey("OperationsDetail")]
        public int? OperationsDetailId { get; set; }
        public virtual OperationDetails OperationsDetail { get; set; }

        public int TenantId { get; set; }
    }
}

