//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Niva.Erp.Models.Conta
{
    using Abp.Domain.Entities;
    using Niva.Erp.Models.AutoOperation;
    using Niva.Erp.Models.Contracts;
    using System.ComponentModel.DataAnnotations.Schema;

    public class OperationDetails : Entity<int>
    {
		public virtual decimal Value { get; set; }

        public virtual decimal ValueCurr { get; set; }

        public virtual decimal VAT { get; set; }

        public virtual string Details { get; set; }

        [ForeignKey("Debit")]
        public int DebitId { get; set; }
        public virtual Account Debit { get; set; }

        [ForeignKey("Credit")]
        public int CreditId { get; set; }
        public virtual Account Credit { get; set; }

        [ForeignKey("Operation")]
        public int OperationId { get; set; }
        public virtual Operation Operation { get; set; }

        public int? DetailNr { get; set; }

        public virtual decimal DebitValueDeduct { get; set; }

        public virtual decimal CreditValueDeduct { get; set; }

        public virtual decimal DebitValueNededuct
        {
            get
            {
                return Value - DebitValueDeduct;
            }
        }

        public virtual decimal CreditValueNededuct
        {
            get
            {
                return Value - CreditValueDeduct;
            }
        }

        [ForeignKey("OperGenerate")]
        public int? OperGenerateId { get; set; }
        public virtual OperGenerate OperGenerate { get; set; }

        [ForeignKey("InvoiceElementsDetails")]
        public int? InvoiceElementsDetailsId { get; set; }
        public virtual InvoiceElementsDetails InvoiceElementsDetails { get; set; }

        [ForeignKey("InvoiceElementsDetailsCategory")]
        public int? InvoiceElementsDetailsCategoryId { get; set; }
        public virtual InvoiceElementsDetailsCategory InvoiceElementsDetailsCategory { get; set; }
    }
}

